package com.mycompany.testetotem5.View;

import com.mycompany.testetotem5.Controller.NavegacaoController;
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author boo
 */
public class Tela2EscolhaRobos extends javax.swing.JDialog
{
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Tela2EscolhaRobos.class.getName());

    /**
     * Creates new form Tela2EscolhaRobos
     * @param parent
     * @param modal
     */
    public Tela2EscolhaRobos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        configurarBotoes();
    }
    
        //adicionando um construtor telainicio SEM PARAMETROS que o main vai chamar
    public Tela2EscolhaRobos(){
        super(new javax.swing.JFrame(), false);
        initComponents();
        configurarBotoes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbl_imgRobo3 = new javax.swing.JLabel();
        lbl_imgRobo1 = new javax.swing.JLabel();
        lbl_imgRobo2 = new javax.swing.JLabel();
        lbl_imgRobo4 = new javax.swing.JLabel();
        btnRobo1 = new javax.swing.JButton();
        btnRobo2 = new javax.swing.JButton();
        btnRobo3 = new javax.swing.JButton();
        btnRobo4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("VEJA MAIS SOBRE OS ROBOS!");

        lbl_imgRobo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/robozinhoInho.png"))); // NOI18N
        lbl_imgRobo3.setText("robo3");
        lbl_imgRobo3.setPreferredSize(new java.awt.Dimension(65, 36));

        lbl_imgRobo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/robozinhoInho.png"))); // NOI18N
        lbl_imgRobo1.setText("robo1");
        lbl_imgRobo1.setPreferredSize(new java.awt.Dimension(65, 36));

        lbl_imgRobo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/robozinhoInho.png"))); // NOI18N
        lbl_imgRobo2.setText("robo2");
        lbl_imgRobo2.setPreferredSize(new java.awt.Dimension(65, 36));

        lbl_imgRobo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/robozinhoInho.png"))); // NOI18N
        lbl_imgRobo4.setText("robo4");
        lbl_imgRobo4.setPreferredSize(new java.awt.Dimension(65, 36));

        btnRobo1.setText("Robo 1");
        btnRobo1.addActionListener(this::btnRobo1ActionPerformed);

        btnRobo2.setText("Robo 2");

        btnRobo3.setText("Robo 3");

        btnRobo4.setText("Robo 4");

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jButton1.setText("Acabei minha Exploração");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(322, 322, 322)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButton1)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lbl_imgRobo3, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_imgRobo1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRobo1)
                    .addComponent(btnRobo3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 245, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lbl_imgRobo2, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_imgRobo4, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRobo2)
                    .addComponent(btnRobo4))
                .addGap(187, 187, 187))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lbl_imgRobo1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_imgRobo2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRobo1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, Short.MAX_VALUE)
                    .addComponent(btnRobo2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lbl_imgRobo3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_imgRobo4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRobo3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, Short.MAX_VALUE)
                    .addComponent(btnRobo4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addComponent(jButton1)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRobo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRobo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRobo1ActionPerformed

    private void configurarBotoes(){
        // Botao robo1
        btnRobo1.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                Tela3InfoRobo telaInfo = new Tela3InfoRobo(1); //passa quaul robo (1,2,3,4)
                NavegacaoController.trocarTela(Tela2EscolhaRobos.this, telaInfo);
            }
        });
        
        //Botão robo2
        btnRobo2.addActionListener(new ActionListener(){
        @Override
        public void actionPerformed(ActionEvent e){
            Tela3InfoRobo telaInfo = new Tela3InfoRobo(2);
            NavegacaoController.trocarTela(Tela2EscolhaRobos.this, telaInfo);
        }
    });
        
        //Botão robo3
        btnRobo3.addActionListener(new ActionListener(){
           @Override
           public void actionPerformed(ActionEvent e){
               Tela3InfoRobo telaInfo = new Tela3InfoRobo(3);
               NavegacaoController.trocarTela(Tela2EscolhaRobos.this, telaInfo);
           }
        });
        
        //Botão Robo 4
        btnRobo4.addActionListener(new ActionListener(){
           @Override
           public void actionPerformed(ActionEvent e){
               Tela3InfoRobo telaInfo = new Tela3InfoRobo(4);
               NavegacaoController.trocarTela(Tela2EscolhaRobos.this, telaInfo);
           }
        });
        
        // Botão Votação
        btnVotacao.addActionListener(new ActionListener(){
           @Override
           public void actionPerformed(ActionEvent e){
               NavegacaoController.trocarTela(Tela2EscolhaRobos.this, new Tela4Votacao());
           }
        });
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex)
        {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            @Override
            public void run() {
                Tela2EscolhaRobos dialog = new Tela2EscolhaRobos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter()
                {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRobo1;
    private javax.swing.JButton btnRobo2;
    private javax.swing.JButton btnRobo3;
    private javax.swing.JButton btnRobo4;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_imgRobo1;
    private javax.swing.JLabel lbl_imgRobo2;
    private javax.swing.JLabel lbl_imgRobo3;
    private javax.swing.JLabel lbl_imgRobo4;
    // End of variables declaration//GEN-END:variables
}
